---
galaxy_info:
  author: "Rob Cushman"
  description: "Provisions a BootC VM on Proxmox"
  license: "MIT"
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"
dependencies: []
